# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luca/Documents/TimedAutomata

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luca/Documents/TimedAutomata

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca/Documents/TimedAutomata/CMakeFiles /home/luca/Documents/TimedAutomata//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca/Documents/TimedAutomata/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simple_example

# Build rule for target.
simple_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_example
.PHONY : simple_example

# fast build rule for target.
simple_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_example.dir/build.make CMakeFiles/simple_example.dir/build
.PHONY : simple_example/fast

#=============================================================================
# Target rules for targets named test_example

# Build rule for target.
test_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_example
.PHONY : test_example

# fast build rule for target.
test_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_example.dir/build.make CMakeFiles/test_example.dir/build
.PHONY : test_example/fast

#=============================================================================
# Target rules for targets named railway_example

# Build rule for target.
railway_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 railway_example
.PHONY : railway_example

# fast build rule for target.
railway_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/railway_example.dir/build.make CMakeFiles/railway_example.dir/build
.PHONY : railway_example/fast

#=============================================================================
# Target rules for targets named zonegraph_example

# Build rule for target.
zonegraph_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zonegraph_example
.PHONY : zonegraph_example

# fast build rule for target.
zonegraph_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zonegraph_example.dir/build.make CMakeFiles/zonegraph_example.dir/build
.PHONY : zonegraph_example/fast

#=============================================================================
# Target rules for targets named utap_example

# Build rule for target.
utap_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utap_example
.PHONY : utap_example

# fast build rule for target.
utap_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utap_example.dir/build.make CMakeFiles/utap_example.dir/build
.PHONY : utap_example/fast

#=============================================================================
# Target rules for targets named integration_example

# Build rule for target.
integration_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 integration_example
.PHONY : integration_example

# fast build rule for target.
integration_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/integration_example.dir/build.make CMakeFiles/integration_example.dir/build
.PHONY : integration_example/fast

#=============================================================================
# Target rules for targets named integration_example_2

# Build rule for target.
integration_example_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 integration_example_2
.PHONY : integration_example_2

# fast build rule for target.
integration_example_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/integration_example_2.dir/build.make CMakeFiles/integration_example_2.dir/build
.PHONY : integration_example_2/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examples.dir/build.make CMakeFiles/examples.dir/build
.PHONY : examples/fast

example/integration_example.o: example/integration_example.cpp.o
.PHONY : example/integration_example.o

# target to build an object file
example/integration_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/integration_example.dir/build.make CMakeFiles/integration_example.dir/example/integration_example.cpp.o
.PHONY : example/integration_example.cpp.o

example/integration_example.i: example/integration_example.cpp.i
.PHONY : example/integration_example.i

# target to preprocess a source file
example/integration_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/integration_example.dir/build.make CMakeFiles/integration_example.dir/example/integration_example.cpp.i
.PHONY : example/integration_example.cpp.i

example/integration_example.s: example/integration_example.cpp.s
.PHONY : example/integration_example.s

# target to generate assembly for a file
example/integration_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/integration_example.dir/build.make CMakeFiles/integration_example.dir/example/integration_example.cpp.s
.PHONY : example/integration_example.cpp.s

example/integration_example_2.o: example/integration_example_2.cpp.o
.PHONY : example/integration_example_2.o

# target to build an object file
example/integration_example_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/integration_example_2.dir/build.make CMakeFiles/integration_example_2.dir/example/integration_example_2.cpp.o
.PHONY : example/integration_example_2.cpp.o

example/integration_example_2.i: example/integration_example_2.cpp.i
.PHONY : example/integration_example_2.i

# target to preprocess a source file
example/integration_example_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/integration_example_2.dir/build.make CMakeFiles/integration_example_2.dir/example/integration_example_2.cpp.i
.PHONY : example/integration_example_2.cpp.i

example/integration_example_2.s: example/integration_example_2.cpp.s
.PHONY : example/integration_example_2.s

# target to generate assembly for a file
example/integration_example_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/integration_example_2.dir/build.make CMakeFiles/integration_example_2.dir/example/integration_example_2.cpp.s
.PHONY : example/integration_example_2.cpp.s

example/railway_example.o: example/railway_example.cpp.o
.PHONY : example/railway_example.o

# target to build an object file
example/railway_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/railway_example.dir/build.make CMakeFiles/railway_example.dir/example/railway_example.cpp.o
.PHONY : example/railway_example.cpp.o

example/railway_example.i: example/railway_example.cpp.i
.PHONY : example/railway_example.i

# target to preprocess a source file
example/railway_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/railway_example.dir/build.make CMakeFiles/railway_example.dir/example/railway_example.cpp.i
.PHONY : example/railway_example.cpp.i

example/railway_example.s: example/railway_example.cpp.s
.PHONY : example/railway_example.s

# target to generate assembly for a file
example/railway_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/railway_example.dir/build.make CMakeFiles/railway_example.dir/example/railway_example.cpp.s
.PHONY : example/railway_example.cpp.s

example/simple_example.o: example/simple_example.cpp.o
.PHONY : example/simple_example.o

# target to build an object file
example/simple_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_example.dir/build.make CMakeFiles/simple_example.dir/example/simple_example.cpp.o
.PHONY : example/simple_example.cpp.o

example/simple_example.i: example/simple_example.cpp.i
.PHONY : example/simple_example.i

# target to preprocess a source file
example/simple_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_example.dir/build.make CMakeFiles/simple_example.dir/example/simple_example.cpp.i
.PHONY : example/simple_example.cpp.i

example/simple_example.s: example/simple_example.cpp.s
.PHONY : example/simple_example.s

# target to generate assembly for a file
example/simple_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple_example.dir/build.make CMakeFiles/simple_example.dir/example/simple_example.cpp.s
.PHONY : example/simple_example.cpp.s

example/test_example.o: example/test_example.cpp.o
.PHONY : example/test_example.o

# target to build an object file
example/test_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_example.dir/build.make CMakeFiles/test_example.dir/example/test_example.cpp.o
.PHONY : example/test_example.cpp.o

example/test_example.i: example/test_example.cpp.i
.PHONY : example/test_example.i

# target to preprocess a source file
example/test_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_example.dir/build.make CMakeFiles/test_example.dir/example/test_example.cpp.i
.PHONY : example/test_example.cpp.i

example/test_example.s: example/test_example.cpp.s
.PHONY : example/test_example.s

# target to generate assembly for a file
example/test_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_example.dir/build.make CMakeFiles/test_example.dir/example/test_example.cpp.s
.PHONY : example/test_example.cpp.s

example/utap_example.o: example/utap_example.cpp.o
.PHONY : example/utap_example.o

# target to build an object file
example/utap_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utap_example.dir/build.make CMakeFiles/utap_example.dir/example/utap_example.cpp.o
.PHONY : example/utap_example.cpp.o

example/utap_example.i: example/utap_example.cpp.i
.PHONY : example/utap_example.i

# target to preprocess a source file
example/utap_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utap_example.dir/build.make CMakeFiles/utap_example.dir/example/utap_example.cpp.i
.PHONY : example/utap_example.cpp.i

example/utap_example.s: example/utap_example.cpp.s
.PHONY : example/utap_example.s

# target to generate assembly for a file
example/utap_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utap_example.dir/build.make CMakeFiles/utap_example.dir/example/utap_example.cpp.s
.PHONY : example/utap_example.cpp.s

example/zonegraph_example.o: example/zonegraph_example.cpp.o
.PHONY : example/zonegraph_example.o

# target to build an object file
example/zonegraph_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zonegraph_example.dir/build.make CMakeFiles/zonegraph_example.dir/example/zonegraph_example.cpp.o
.PHONY : example/zonegraph_example.cpp.o

example/zonegraph_example.i: example/zonegraph_example.cpp.i
.PHONY : example/zonegraph_example.i

# target to preprocess a source file
example/zonegraph_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zonegraph_example.dir/build.make CMakeFiles/zonegraph_example.dir/example/zonegraph_example.cpp.i
.PHONY : example/zonegraph_example.cpp.i

example/zonegraph_example.s: example/zonegraph_example.cpp.s
.PHONY : example/zonegraph_example.s

# target to generate assembly for a file
example/zonegraph_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zonegraph_example.dir/build.make CMakeFiles/zonegraph_example.dir/example/zonegraph_example.cpp.s
.PHONY : example/zonegraph_example.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... examples"
	@echo "... integration_example"
	@echo "... integration_example_2"
	@echo "... railway_example"
	@echo "... simple_example"
	@echo "... test_example"
	@echo "... utap_example"
	@echo "... zonegraph_example"
	@echo "... example/integration_example.o"
	@echo "... example/integration_example.i"
	@echo "... example/integration_example.s"
	@echo "... example/integration_example_2.o"
	@echo "... example/integration_example_2.i"
	@echo "... example/integration_example_2.s"
	@echo "... example/railway_example.o"
	@echo "... example/railway_example.i"
	@echo "... example/railway_example.s"
	@echo "... example/simple_example.o"
	@echo "... example/simple_example.i"
	@echo "... example/simple_example.s"
	@echo "... example/test_example.o"
	@echo "... example/test_example.i"
	@echo "... example/test_example.s"
	@echo "... example/utap_example.o"
	@echo "... example/utap_example.i"
	@echo "... example/utap_example.s"
	@echo "... example/zonegraph_example.o"
	@echo "... example/zonegraph_example.i"
	@echo "... example/zonegraph_example.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

